version: '3.4'

services:
  inventory.api:
    image: ${DOCKER_REGISTRY-}inventoryapi
    build:
      context: .
      dockerfile: Inventory.Api/Dockerfile

  ui:
    image: ${DOCKER_REGISTRY-}nginxui
    ports:
        - 80:80
        - 8080:8080
    build:
      context: ./NginxUI
      dockerfile: Dockerfile
    volumes:
        - ./NginxUI/nginx_logs:/var/log/nginx
  